version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: mayak_local
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - .:/usr/src/app # Mount the local app directory
      - /usr/src/app/node_modules # Use the node_modules from the container
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:123123@localhost:5432/mayak_local?schema=public
      - DATABASE_DIRECT_URL=postgresql://postgres:123123@localhost:5432/mayak_local?schema=public
      - REVALIDATION_TIME=10
    depends_on:
      - postgres
volumes:
  postgres-data:
