version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: mayak
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - .:/usr/src/app # Mount the local app directory
      - /usr/src/app/node_modules # Use the node_modules from the container
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://developer:dev_pass@postgres:5432/mayak?schema=public
      - DATABASE_DIRECT_URL=postgresql://developer:dev_pass@postgres:5432/mayak?schema=public
    depends_on:
      - postgres
volumes:
  postgres-data:
