import { WEEKDAYS_TRANSLATION } from '@/app/(admin)/admin/_lib/consts';

const weekDays = Object.values(WEEKDAYS_TRANSLATION);

export const organizationDefaultValues = {
  name: '',
  type: [],
  typeNames: [],
  ownershipType: null,
  yearsOnMarket: null,
  yearsOfExperience: null,
  isInclusiveSpace: null,
  formatOfWork: null,
  phone: null,
  email: null,
  website: null,
  addresses: [],
  isFreeReception: null,
  discounts: null,
  discountsOther: '',
  workTime: weekDays.map(weekDay => ({
    weekDay,
    time: null,
    isDayOff: true,
  })),
  socialLink: {
    instagram: null,
    facebook: null,
    telegram: null,
    linkedin: null,
    youtube: null,
    tiktok: null,
    viber: null,
  },
  description: null,
  clients: {
    workingWith: [],
    notWorkingWith: [],
  },
  expertSpecializations: [],
  expertSpecializationNames: [],
  supportFocuses: [],
  experience: '',
  specialistSelection: '',
  averageExperience: '',
  achievements: '',
  workMethods: '',
  developmentPolicy: null,
  developmentPolicyOther: '',
  supervisionPolicy: null,
  supervisionPolicyOther: '',
  ethicalControl: '',
  feedbackCollection: '',
  documentFiles: [],
  submitterContact: '',
};
